#!/usr/bin/env node
// ============================================================================
// PegaProx theme export — generates pegaprox/theme_registry.py
// ============================================================================
//
// PEGAPROX_THEMES in web/index.html.original is the single source of truth for
// themes. The backend needs the same knowledge for its whitelists (user
// preferences, default theme), so this script extracts the registry at build
// time and writes it as a plain Python module. Run via web/Dev/build.sh; the
// generated file is committed like web/index.html.
//
// No dependencies; Node >= 16.

'use strict';
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');
const source = path.join(root, 'web', 'index.html.original');
const target = path.join(root, 'pegaprox', 'theme_registry.py');

const html = fs.readFileSync(source, 'utf8');
const marker = 'const PEGAPROX_THEMES = ';
const start = html.indexOf(marker);
if (start === -1) {
    console.error('export-themes: PEGAPROX_THEMES not found in ' + source);
    process.exit(1);
}

// Brace-match the object literal.
let i = html.indexOf('{', start);
let depth = 0;
let end = -1;
let inString = null;
for (; i < html.length; i++) {
    const ch = html[i];
    if (inString) {
        if (ch === '\\') { i++; continue; }
        if (ch === inString) inString = null;
        continue;
    }
    if (ch === "'" || ch === '"' || ch === '`') { inString = ch; continue; }
    if (ch === '{') depth++;
    if (ch === '}') {
        depth--;
        if (depth === 0) { end = i; break; }
    }
}
if (end === -1) {
    console.error('export-themes: unbalanced braces in PEGAPROX_THEMES');
    process.exit(1);
}

// The block is a pure object literal (strings, booleans, nested objects).
const themes = new Function('return ' + html.slice(html.indexOf('{', start), end + 1))();

const all = Object.keys(themes);
const corporate = all.filter((k) => themes[k].corporate === true);
const light = all.filter((k) => themes[k].light === true);
const pyList = (items) => '[\n' + items.map((k) => `    '${k}',`).join('\n') + '\n]';

const out = `# -*- coding: utf-8 -*-
"""GENERATED by web/Dev/build.sh (export-themes.js) — DO NOT EDIT.

The theme registry lives in web/index.html.original (PEGAPROX_THEMES); edit it
there and rebuild. Layer 0: no pegaprox imports allowed in this file.
"""

# Every theme the frontend can render — the whitelist for user preferences and
# the server-wide default theme.
ALLOWED_THEMES = ${pyList(all)}

# Themes the Corporate layout renders (registry entries flagged corporate: true).
CORPORATE_THEMES = ${pyList(corporate)}

# Themes that render on a light background (registry entries flagged light: true).
LIGHT_THEMES = ${pyList(light)}
`;

const previous = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
if (previous !== out) {
    fs.writeFileSync(target, out);
    console.log(`export-themes: wrote ${path.relative(root, target)} (${all.length} themes, ${corporate.length} corporate, ${light.length} light)`);
} else {
    console.log(`export-themes: ${path.relative(root, target)} up to date (${all.length} themes)`);
}
