# -*- coding: utf-8 -*-
"""GENERATED by web/Dev/build.sh (export-themes.js) — DO NOT EDIT.

The theme registry lives in web/index.html.original (PEGAPROX_THEMES); edit it
there and rebuild. Layer 0: no pegaprox imports allowed in this file.
"""

# Every theme the frontend can render — the whitelist for user preferences and
# the server-wide default theme.
ALLOWED_THEMES = [
    'proxmoxDark',
    'midnight',
    'forest',
    'rose',
    'ocean',
    'highContrast',
    'dracula',
    'nord',
    'monokai',
    'matrix',
    'sunset',
    'cyberpunk',
    'github',
    'solarizedDark',
    'gruvbox',
    'corporateDark',
    'corporateLight',
    'enterpriseBlue',
    'cloud',
]

# Themes the Corporate layout renders (registry entries flagged corporate: true).
CORPORATE_THEMES = [
    'corporateDark',
    'corporateLight',
    'enterpriseBlue',
]

# Themes that render on a light background (registry entries flagged light: true).
LIGHT_THEMES = [
    'corporateLight',
]
