"""Central image files and provisioning on independent Proxmox nodes.

Images stay on the PegaProx server; only the selected node needs a copy.
No shared PVE storage or pre-existing node-local VM template is required.
"""
import hashlib
import logging
import os
import re
import shlex
import shutil
import tempfile
import threading
import time
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from urllib.parse import urljoin, urlparse

import requests

from pegaprox.core.db import get_db
from pegaprox.utils.url_security import sanitize_outbound_url, resolve_and_pin_url

_CACHE_LOCKS = [threading.Lock() for _ in range(32)]
_CREATE_LOCKS = [threading.Lock() for _ in range(32)]
PROVISION_SLOTS = threading.BoundedSemaphore(2)
SAFE_NAME = re.compile(r'^[A-Za-z0-9][A-Za-z0-9._-]{0,62}$')


def now():
    return datetime.now(timezone.utc).isoformat()


def library_dir():
    # Read at call time so the test DB's isolated CONFIG_DIR is respected too.
    from pegaprox.core import db as dbmod
    root = Path(dbmod.CONFIG_DIR) / 'image-library'
    root.mkdir(parents=True, exist_ok=True)
    return root


def max_image_bytes():
    return max(1, int(os.environ.get('PEGAPROX_IMAGE_MAX_GB', '20'))) * 1024 ** 3


def cache_path(image):
    # IDs are generated by us (or from the curated catalog), never a client path.
    if not SAFE_NAME.fullmatch(image['id']):
        raise ValueError('Invalid image ID')
    return library_dir() / (image['id'] + '.image')


def cache_lock(image_id):
    return _CACHE_LOCKS[int(hashlib.sha256(image_id.encode()).hexdigest()[:8], 16) % 32]


def write_image(chunks, destination, expected_sha256=''):
    """Bounded, verified, atomic writes: failed uploads never become cache hits."""
    digest = hashlib.sha256()
    size = 0
    fd, temporary = tempfile.mkstemp(prefix='.incoming-', dir=destination.parent)
    try:
        with os.fdopen(fd, 'wb') as output:
            for chunk in chunks:
                if not chunk:
                    continue
                size += len(chunk)
                if size > max_image_bytes():
                    raise ValueError('Image exceeds PEGAPROX_IMAGE_MAX_GB')
                # Leave room for the DB/logs sharing the config filesystem.
                if shutil.disk_usage(destination.parent).free < len(chunk) + 256 * 1024 ** 2:
                    raise ValueError('Not enough free space in the central image library')
                digest.update(chunk)
                output.write(chunk)
        if not size:
            raise ValueError('Image is empty')
        checksum = digest.hexdigest()
        if expected_sha256 and checksum != expected_sha256.lower():
            raise ValueError('Image SHA-256 does not match')
        os.replace(temporary, destination)
        return size, checksum
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def validate_source_url(url):
    # Central downloads are public-only. Internal/offline images can be uploaded.
    parsed = urlparse(url)
    if parsed.username or parsed.password or parsed.fragment:
        raise ValueError('Image URLs must not contain credentials or fragments')
    return sanitize_outbound_url(url, allowed_schemes=('https', 'http'))


def ensure_cached(image):
    with cache_lock(image['id']):
        destination = cache_path(image)
        if destination.is_file():
            digest = hashlib.sha256()
            with destination.open('rb') as source:
                for chunk in iter(lambda: source.read(1024 * 1024), b''):
                    digest.update(chunk)
            checksum = digest.hexdigest()
            if image.get('sha256') and checksum != image['sha256'].lower():
                raise ValueError('Cached image SHA-256 does not match; remove and re-import the image')
            return destination, destination.stat().st_size, checksum
        if not image.get('source_url'):
            raise ValueError('Uploaded image file is missing; upload it again')
        url = image['source_url']
        with requests.Session() as session:
            session.trust_env = False
            for _ in range(6):
                validate_source_url(url)
                # HTTP is pinned; HTTPS verifies the certificate for the hostname.
                pinned = resolve_and_pin_url(url, allowed_schemes=('https', 'http'))
                headers = {'Host': urlparse(url).netloc} if pinned != url else {}
                with session.get(pinned, headers=headers, stream=True, timeout=(15, 60),
                                 allow_redirects=False) as response:
                    if response.status_code in (301, 302, 303, 307, 308):
                        location = response.headers.get('Location')
                        if not location:
                            raise ValueError('Image redirect is missing its destination')
                        url = urljoin(url, location)
                        continue
                    if response.status_code != 200:
                        raise ValueError(f'Image download failed (HTTP {response.status_code})')
                    length = response.headers.get('Content-Length')
                    if length and int(length) > max_image_bytes():
                        raise ValueError('Image exceeds PEGAPROX_IMAGE_MAX_GB')
                    size, checksum = write_image(response.iter_content(1024 * 1024),
                                                 destination, image.get('sha256', ''))
                    return destination, size, checksum
        raise ValueError('Too many image redirects')


def pve_get(manager, path):
    response = manager._api_get(f'https://{manager.host}:{manager.api_port}/api2/json{path}')
    if response.status_code != 200:
        raise ValueError(f'Proxmox resource lookup failed (HTTP {response.status_code})')
    return response.json().get('data')


def target_options(manager, node=None):
    nodes = [n for n in pve_get(manager, '/nodes') or [] if n.get('status') == 'online']
    result = {'nodes': [n['node'] for n in nodes], 'storages': [], 'bridges': []}
    if node is None:
        return result
    if node not in result['nodes']:
        raise ValueError('Selected node is not online or does not belong to this connection')
    result['storages'] = [
        {'storage': s['storage'], 'content': s.get('content', ''), 'avail': s.get('avail', 0)}
        for s in pve_get(manager, f'/nodes/{node}/storage') or []
        if s.get('active') and s.get('enabled', 1)
    ]
    result['bridges'] = [n['iface'] for n in pve_get(manager, f'/nodes/{node}/network') or []
                         if n.get('type') in ('bridge', 'OVSBridge')]
    return result


def validate_vm_request(body, image, options):
    if not isinstance(body, dict):
        raise ValueError('Expected a JSON object')
    config = {}
    for field in ('node', 'name', 'storage', 'bridge'):
        value = body.get(field)
        if not isinstance(value, str) or not SAFE_NAME.fullmatch(value):
            raise ValueError(f'Invalid {field}')
        config[field] = value
    if config['node'] not in options['nodes'] or config['bridge'] not in options['bridges']:
        raise ValueError('Node or network bridge is unavailable')
    storages = {s['storage']: s['content'].split(',') for s in options['storages']}
    if 'images' not in storages.get(config['storage'], []):
        raise ValueError('Selected disk storage does not support VM images')
    for field, default, minimum, maximum in (
        ('cores', 2, 1, 256), ('memory', 2048, 128, 4194304), ('disk_gb', 10, 1, 65536),
    ):
        value = body.get(field, image.get(field, default))
        if isinstance(value, bool) or not str(value).isdigit():
            raise ValueError(f'{field} must be an integer')
        config[field] = int(value)
        if not minimum <= config[field] <= maximum:
            raise ValueError(f'{field} is out of range')
    vmid = body.get('vmid')
    if vmid not in (None, ''):
        if isinstance(vmid, bool) or not str(vmid).isdigit() or not 100 <= int(vmid) <= 999999999:
            raise ValueError('VMID must be an integer between 100 and 999999999')
        config['vmid'] = int(vmid)
    start = body.get('start', False)
    if not isinstance(start, bool):
        raise ValueError('start must be a boolean')
    config['start'] = start
    if image['kind'] == 'iso':
        iso_storage = body.get('iso_storage')
        if not isinstance(iso_storage, str) or not SAFE_NAME.fullmatch(iso_storage):
            raise ValueError('ISO storage is required')
        if 'iso' not in storages.get(iso_storage, []):
            raise ValueError('Selected ISO storage does not support ISO images')
        config['iso_storage'] = iso_storage
        ostype = body.get('ostype', 'l26')
        if ostype not in ('l26', 'win10', 'win11', 'other'):
            raise ValueError('Unsupported OS type')
        config['ostype'] = ostype
    else:
        user = body.get('ciuser') or image.get('default_user') or 'root'
        if not isinstance(user, str) or not re.fullmatch(r'[a-z_][a-z0-9_-]{0,31}', user):
            raise ValueError('Invalid Cloud-init username')
        keys = body.get('sshkeys', '')
        if not isinstance(keys, str) or len(keys) > 16384:
            raise ValueError('Invalid SSH public keys')
        lines = [line.strip() for line in keys.splitlines() if line.strip()]
        if not lines or any(not re.fullmatch(
            r'(?:ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(?:256|384|521)) [A-Za-z0-9+/]+={0,3}(?: [^\r\n]*)?',
            line) for line in lines):
            raise ValueError('Provide at least one valid SSH public key')
        config.update(ciuser=user, sshkeys='\n'.join(lines))
    return config


def update_job(job_id, **fields):
    allowed = {'status', 'progress', 'error', 'vmid', 'finished_at'}
    if not fields or not set(fields) <= allowed:
        raise ValueError('Invalid provisioning job fields')
    assignments = ', '.join(f'{key} = ?' for key in fields)
    db = get_db()
    db.conn.execute(f'UPDATE image_provision_jobs SET {assignments} WHERE id = ?',
                    (*fields.values(), job_id))
    db.conn.commit()


def run_command(ssh, command):
    """Drain stdout and stderr together to avoid blocking on a full SSH pipe."""
    _, stdout, stderr = ssh.exec_command(command, get_pty=False, timeout=1800)
    channel = stdout.channel
    output, errors = bytearray(), bytearray()
    deadline = time.monotonic() + 1800
    while True:
        for ready, receive, buffer in ((channel.recv_ready, channel.recv, output),
                                       (channel.recv_stderr_ready, channel.recv_stderr, errors)):
            while ready():
                chunk = receive(65536)
                if not chunk:
                    break
                if len(buffer) < 65536:
                    buffer.extend(chunk[:65536 - len(buffer)])
        if channel.exit_status_ready() and not channel.recv_ready() and not channel.recv_stderr_ready():
            break
        if time.monotonic() > deadline:
            channel.close()
            raise RuntimeError('Node command timed out')
        time.sleep(0.05)
    rc = channel.recv_exit_status()
    if rc:
        # Do not echo commands (SSH keys, URLs) or unbounded remote output into logs.
        raise RuntimeError(errors.decode('utf-8', errors='replace')[:500] or f'Node command failed ({rc})')
    return output.decode('utf-8', errors='replace').strip()


def transfer_image(ssh, local_path, remote_path, checksum):
    """Content-addressed ISO names allow safe reuse without overwriting another VM's ISO."""
    q = shlex.quote
    parent = str(PurePosixPath(remote_path).parent)
    run_command(ssh, f'mkdir -p -- {q(parent)}')
    actual = run_command(ssh, f'if test -f {q(remote_path)}; then sha256sum -- {q(remote_path)}; fi')
    if actual.split(' ', 1)[0] == checksum:
        return
    temporary = remote_path + '.part-' + os.urandom(6).hex()
    with ssh.open_sftp() as sftp:
        sftp.get_channel().settimeout(600)
        try:
            sftp.put(str(local_path), temporary)
            actual = run_command(ssh, f'sha256sum -- {q(temporary)}')
            if actual.split(' ', 1)[0] != checksum:
                raise ValueError('Transferred image SHA-256 does not match')
            run_command(ssh, f'mv -f -- {q(temporary)} {q(remote_path)}')
        finally:
            try:
                sftp.remove(temporary)
            except OSError:
                pass


def provision_vm(job_id, manager, image, config):
    ssh = None
    remote_temporary = None
    created = False
    completed = False
    vmid = None
    q = shlex.quote
    try:
        update_job(job_id, status='running', progress=5)
        local_path, _, checksum = ensure_cached(image)
        update_job(job_id, progress=25)
        # Re-check the destination after a potentially long download.
        validate_vm_request(config, image, target_options(manager, config['node']))
        host = manager._get_node_ip(config['node'])
        if not host:
            raise ValueError('Could not resolve selected node for SSH')
        ssh = manager._ssh_connect(host)
        if ssh is None:
            raise RuntimeError('SSH connection failed; configure SSH access for this connection')
        if run_command(ssh, 'id -u') != '0':
            raise ValueError('Central image provisioning requires root SSH access on the selected node')
        if image['kind'] == 'iso':
            iso_volid = f"{config['iso_storage']}:iso/pegaprox-{checksum}.iso"
            remote = run_command(ssh, f'pvesm path {q(iso_volid)}')
            if not remote.startswith('/') or any(c in remote for c in '\n\r\x00'):
                raise ValueError('Proxmox returned an invalid ISO storage path')
        else:
            remote = remote_temporary = f'/tmp/pegaprox-image-{job_id}.img'
        # Keep deletion from removing the file while SFTP is reading it.
        with cache_lock(image['id']):
            transfer_image(ssh, local_path, remote, checksum)
        update_job(job_id, progress=50)
        ostype = config.get('ostype', 'l26')
        create_args = (f'--name {q(config["name"])} --cores {config["cores"]} '
                  f'--memory {config["memory"]} --scsihw virtio-scsi-pci --ostype {q(ostype)} '
                  f'--net0 {q("virtio,bridge=" + config["bridge"])}')
        if image['kind'] == 'iso':
            create_args += (f' --scsi0 {q(config["storage"] + ":" + str(config["disk_gb"]))}'
                       f' --ide2 {q(iso_volid + ",media=cdrom")} --boot {q("order=ide2;scsi0")}')
        if image.get('cpu'):
            create_args += f' --cpu {q(image["cpu"])}'
        # Serialize nextid + create for jobs sharing a PVE connection. qm create
        # still protects against IDs taken by another client or connection.
        lock_index = int(hashlib.sha256(manager.host.encode()).hexdigest()[:8], 16) % 32
        with _CREATE_LOCKS[lock_index]:
            vmid = config.get('vmid') or int(pve_get(manager, '/cluster/nextid'))
            if not 100 <= vmid <= 999999999:
                raise ValueError('Proxmox returned an invalid VMID')
            update_job(job_id, vmid=vmid)
            run_command(ssh, f'qm create {vmid} {create_args}')
            # Only a successful atomic qm create gives us ownership for rollback.
            created = True
        update_job(job_id, progress=65)
        if image['kind'] == 'cloud':
            run_command(ssh, f'qm importdisk {vmid} {q(remote)} {q(config["storage"])}')
            raw_config = run_command(ssh, f'qm config {vmid}')
            match = re.search(r'^unused0:\s*([^,\s]+)', raw_config, re.MULTILINE)
            if not match or not match.group(1).startswith(config['storage'] + ':'):
                raise ValueError('Could not identify the imported boot disk')
            run_command(ssh, f'qm set {vmid} --scsi0 {q(match.group(1))} '
                        f'--ide2 {q(config["storage"] + ":cloudinit")} --boot {q("order=scsi0")} '
                        '--serial0 socket --vga serial0 --agent 1')
            run_command(ssh, f'qm resize {vmid} scsi0 {config["disk_gb"]}G')
            key_path = f'/tmp/pegaprox-keys-{job_id}.pub'
            try:
                with ssh.open_sftp() as sftp:
                    with sftp.file(key_path, 'w') as key_file:
                        key_file.write(config['sshkeys'])
                    sftp.chmod(key_path, 0o600)
                run_command(ssh, f'qm set {vmid} --ciuser {q(config["ciuser"])} '
                            f'--sshkeys {q(key_path)} --ipconfig0 ip=dhcp')
            finally:
                run_command(ssh, f'rm -f -- {q(key_path)}')
        update_job(job_id, progress=90)
        if config['start']:
            run_command(ssh, f'qm start {vmid}')
        completed = True
        update_job(job_id, status='completed', progress=100, finished_at=now())
    except Exception as exc:
        # requests exceptions can include a signed source URL in their text.
        error = ('Central image download failed; check connectivity and source availability'
                 if isinstance(exc, requests.RequestException) else str(exc)[:500])
        if completed:
            error = f'VM {vmid} was created, but job recording failed; check the VM before retrying'
        elif created and ssh:
            try:
                run_command(ssh, f'qm destroy {vmid} --purge 1')
            except Exception:
                error += f' (partial VM {vmid} remains; remove it manually)'
        logging.warning('Image provisioning job %s failed', job_id)
        try:
            update_job(job_id, status='failed', error=error, finished_at=now())
        except Exception:
            logging.exception('Could not record image provisioning job %s', job_id)
    finally:
        if ssh:
            if remote_temporary:
                try:
                    run_command(ssh, f'rm -f -- {q(remote_temporary)}')
                except Exception:
                    pass
            try:
                ssh.close()
            except Exception:
                logging.warning('Could not close image provisioning SSH session')
        PROVISION_SLOTS.release()
